services:
  nginx:
    image: nginx:latest
    container_name: corcel_nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html  # Make sure you're pointing to the correct folder
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: corcel_frontend
    ports:
      - "8081:80"
    ulimits:
      nofile:
        soft: 65535  # Set soft limit for file descriptors
        hard: 65535  # Set hard limit for file descriptors
    depends_on:
      - backend
    networks:
      - app_network
      

  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: corcel_backend
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=pt_BR.utf8 --lc-ctype=pt_BR.utf8
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:17
    container_name: corcel_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    env_file:
      - ./.env

  backups:
    build:
      context: .
      dockerfile: Dockerfile.backups
    container_name: corcel_backups
    depends_on:
      - db
    volumes:
      - ./backups:/dumps
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
